apiVersion: batch/v1
kind: Job
metadata:
  name: order-service-db-migrate
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0" # Wave 0: Executes strictly BEFORE application Pods deploy
spec:
  template:
    metadata:
      name: db-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: postgres:16-alpine
          command:
            - "sh"
            - "-c"
            - "echo 'Running database schema migration in Wave 0...'; sleep 3; echo 'Migration completed successfully.'"
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:workshop_secret@postgres.production.svc.cluster.local:5432/workshop_db"
